budget/urls.py
from django.urls import path

from .views import (ItemListView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView, IncomeDetailView,
                    IncomeCreateView, IncomeUpdateView, IncomeDeleteView)

app_name = "budget"

urlpatterns = [
    # Item's paths
    path("", ItemListView.as_view(), name="item_list"),
    path("items/<uuid:pk>/detail", ItemDetailView.as_view(), name="item_detail"),
    path("items/create", ItemCreateView.as_view(), name="item_create"),
    path("items/<uuid:pk>/update", ItemUpdateView.as_view(), name="item_update"),
    path("items/<uuid:pk>/delete", ItemDeleteView.as_view(), name="item_delete"),

    # Income's paths
    path("incomes/<uuid:pk>/detail", IncomeDetailView.as_view(), name="income_detail"),
    path("incomes/create", IncomeCreateView.as_view(), name="income_create"),
    path("incomes/<uuid:pk>/update", IncomeUpdateView.as_view(), name="income_update"),
    path("incomes/<uuid:pk>/delete", IncomeDeleteView.as_view(), name="income_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("budget/", include("budget.urls")),
    path("", include("pages.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

budget/models.py
import decimal

from django.db import models
from django.db.models import Count, Sum
import uuid

from django.urls import reverse

FREQUENCY_CHOICES = (
    ("Monthly", "Monthly"),
    ("Bimonthly", "Bimonthly"),
    ("Quarterly", "Quarterly"),
    ("Biannually", "Biannually"),
    ("Annually", "Annually"),
)

frequency_factor = {
    "Monthly": 1,
    "Bimonthly": 1 / 2,
    "Quarterly": 1 / 3,
    "Biannually": 1 / 6,
    "Annually": 1 / 12,
}


class Income(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    frequency = models.CharField(max_length=20, choices=FREQUENCY_CHOICES, default="Monthly")
    concept = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    monthly_amount = models.DecimalField(max_digits=10, decimal_places=2, editable=False, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.monthly_amount = self.amount * decimal.Decimal(frequency_factor[self.frequency])
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"INCOME: {self.concept} - {self.frequency} => {self.amount}"

    def get_absolute_url(self):
        return reverse('budget:income_detail', args=[str(self.id)])


class ItemCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"

    def get_num_of_spent(self):
        return Item.objects.filter(category=self).aggregate(num_of_spents=Count('id'))

    def get_total_spent(self):
        return Item.objects.filter(category=self).aggregate(total_amount=Sum('amount'))


class Item(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    frequency = models.CharField(max_length=20, choices=FREQUENCY_CHOICES, default="Monthly")
    category = models.ForeignKey(ItemCategory, on_delete=models.CASCADE, related_name="categories")
    concept = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    monthly_amount = models.DecimalField(max_digits=10, decimal_places=2, editable=False, null=True, blank=True)
    is_essential = models.BooleanField()
    transaction_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.monthly_amount = self.amount * decimal.Decimal(frequency_factor[self.frequency])
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"Item: {self.concept} - {self.frequency} => {self.monthly_amount}"

    def get_absolute_url(self):
        return reverse('budget:item_detail', args=[str(self.id)])

budget/views.py
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Sum, F, Func, ExpressionWrapper, DecimalField, Case, When
from .models import Item, Income


class ItemBaseView(View):
    """Class to define the common elements for the Item's views"""
    model = Item
    fields = "__all__"
    success_url = reverse_lazy("budget:item_list")


class ItemListView(ItemBaseView, ListView):
    """View to list all the items in a budget"""
    context_object_name = "item_list"
    template_name = "budget/item_list.html"

    def get_queryset(self):
        queryset = (
            Item.objects.annotate(
                # Annotated fields to add biannually and annually amounts
                biannually_amount=F("monthly_amount") * 6,
                annually_amount=F("monthly_amount") * 12,
            )
            .select_related("category")
            .order_by('category__name', 'updated_at'))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        kwargs = super().get_context_data(**kwargs)

        queryset = kwargs['object_list']

        # Calculate totals
        total_monthly_amount = 0
        total_amount_by_type = {"essential": 0, "no_essential": 0}
        category_totals = {}
        for item in queryset:
            if item.is_essential:
                total_amount_by_type["essential"] += item.monthly_amount
            else:
                total_amount_by_type["no_essential"] += item.monthly_amount

            total_monthly_amount += item.monthly_amount

            # Calculate the total amount by category
            if item.category.name in category_totals:
                category_totals[item.category.name] += item.monthly_amount
            else:
                category_totals[item.category.name] = item.monthly_amount

        # Convert the category totals into a list of dictionaries
        total_amount_by_category = [
            {'category': category, 'total_amount': total}
            for category, total in category_totals.items()
        ]

        income_list = Income.objects.annotate(
            # Annotated fields to add biannually and annually amounts
            biannually_amount=F("monthly_amount") * 6,
            annually_amount=F("monthly_amount") * 12,)

        income_totals = Income.objects.aggregate(monthly=Sum("monthly_amount"))

        kwargs.update(
            {
                "total_amount_by_category": total_amount_by_category,
                "total_amount_by_type": total_amount_by_type,
                "total_monthly_amount": total_monthly_amount,
                "income_list": income_list,
                "income_totals": income_totals,
                "monthly_cash_flow": income_totals["monthly"] - total_monthly_amount
            }
        )

        return kwargs


class ItemDetailView(ItemBaseView, DetailView):
    """View to display an item's detail"""
    context_object_name = 'item'
    template_name = "budget/item_detail.html"
    queryset = Item.objects.select_related("category")


class ItemCreateView(ItemBaseView, CreateView):
    """View to create a new item"""


class ItemUpdateView(ItemBaseView, UpdateView):
    """View to update a given item"""


class ItemDeleteView(ItemBaseView, DeleteView):
    """View to delete a given item"""


class IncomeBaseView(View):
    """Class to define the common elements for the Income's views"""
    model = Income
    fields = "__all__"
    success_url = reverse_lazy("budget:item_list")


class IncomeListView(IncomeBaseView, ListView):
    """View to list all the income in a budget"""
    context_object_name = "income_list"
    template_name = "budget/item_list.html"


class IncomeDetailView(IncomeBaseView, DetailView):
    """View to display an income's detail"""
    context_object_name = 'income'
    template_name = "budget/income_detail.html"


class IncomeCreateView(IncomeBaseView, CreateView):
    """View to create a new income"""


class IncomeUpdateView(IncomeBaseView, UpdateView):
    """View to update a given income"""


class IncomeDeleteView(ItemBaseView, DeleteView):
    """View to delete a given income"""

templates/budget/income_confirm_delete.html
{% extends "_admin_base.html" %}
{% block title %} Delete Income {% endblock %}

{% block content %}
    <div class="container-fluid p-0">

        <h1 class="h3 mb-3">Budget: Delete Income</h1>

        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Delete Income</h5>
                    </div>
                    <div class="card-body">
                        {% url 'budget:item_list' as list_all %}

                        <div class="container d-flex justify-content-center mt-5" style="width: 50%;">
                            <div class="col mt-5 text-center">
                                <p class="h5">Are you sure you want to delete the Income:</p>
                                <h3 class="my-5">{{ income.concept }}</h3>
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-primary btn-lg" value="Confirm"
                                           style="margin-right: 30px; margin-top: 30px;">
                                    <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;"
                                           onclick="window.location='{{ list_all }}'; return false;" value="Cancel">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/budget/income_detail.html
{% extends "_admin_base.html" %}
{% block title %} Budget Detail {% endblock %}

{% block content %}
    <div class="container-fluid p-0">

        <h1 class="h3 mb-3">Budget: Income Detail</h1>

        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Income detail</h5>
                        <div class="float-end">
                            <div class="col-auto">
                                <a type="button" class="btn btn-secondary btn-sm" href="{% url "budget:item_list" %}">
                                    Back to budget
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <h3><strong>Concept: </strong>{{ income.concept }}</h3>
                        <p><strong>Amount: </strong>{{ income.amount }}</p>
                        <p><strong>Frequency: </strong>{{ income.frequency }}</p>
                        <p><strong>Created at: </strong>{{ income.created_at }}</p>
                        <p><strong>Updated at: </strong>{{ income.updated_at }}</p>

                        <a href="{% url "budget:income_update" income.id %}" class="card-link">Edit</a>
                        <a href="{% url "budget:income_delete" income.id %}" class="card-link">Delete</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/budget/income_form.html
{% extends "_admin_base.html" %}
{% block title %} Budget App: Add a new income item {% endblock %}

{% block content %}
    <div class="container-fluid p-0">

        <h1 class="h3 mb-3">Create Income</h1>

        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0"></h5>
                    </div>
                    <div class="card-body">
                        <div class="container d-flex justify-content-center mt-5" style="width: 25%;">
                            <div class="col mt-5">
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <table class="table">
                                        {{ form.as_table }}
                                    </table>
                                    <div class="container d-flex justify-content-center" style="width: 10%;">
                                        <input type="submit" class="btn btn-primary btn-lg" value="Submit"
                                               style="margin-right: 30px; margin-top: 30px;">
                                        <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;"
                                               onclick="window.location='{% url 'budget:item_list' %}'; return false;"
                                               value="Cancel">
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/budget/item_confirm_delete.html
{% extends "_admin_base.html" %}
{% block title %} Budget Detail {% endblock %}

{% block content %}
    <div class="container-fluid p-0">

        <h1 class="h3 mb-3">Budget: Item Detail</h1>

        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Delete Item</h5>
                    </div>
                    <div class="card-body">
                        {% url 'budget:item_list' as list_all %}

                        <div class="container d-flex justify-content-center mt-5" style="width: 50%;">
                            <div class="col mt-5 text-center">
                                <p class="h5">Are you sure you want to delete the Item:</p>
                                <h3 class="my-5">{{ item.concept }}</h3>
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-primary btn-lg" value="Confirm"
                                           style="margin-right: 30px; margin-top: 30px;">
                                    <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;"
                                           onclick="window.location='{{ list_all }}'; return false;" value="Cancel">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/budget/item_detail.html
{% extends "_admin_base.html" %}
{% block title %} Budget Detail {% endblock %}

{% block content %}
    <div class="container-fluid p-0">

        <h1 class="h3 mb-3">Budget: Item Detail</h1>

        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Item detail</h5>
                        <div class="float-end">
                            <div class="col-auto">
                                <a type="button" class="btn btn-secondary btn-sm" href="{% url "budget:item_list" %}">
                                    Back to budget
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h3><strong>Category: </strong>{{ item.category.name }}</h3>
                        <p><strong>Concept: </strong>{{ item.concept }}</p>
                        <p><strong>Amount: </strong>{{ item.amount }}</p>
                        <p><strong>Is essential?: </strong>
                            {% if item.is_essential %}
                                <i class="align-middle" data-feather="check" style="color: #0b4b38"></i>
                            {% else %}
                                <i class="align-middle" data-feather="x" style="color: #8e0615"></i>
                            {% endif %}
                        </p>
                        <p><strong>Frequency: </strong>{{ item.frequency }}</p>
                        <p><strong>Transaction date: </strong>{{ item.transaction_date }}</p>
                        <p><strong>Created at: </strong>{{ item.created_at }}</p>
                        <p><strong>Updated at: </strong>{{ item.updated_at }}</p>

                        <a href="{% url "budget:item_update" item.id %}" class="card-link">Edit</a>
                        <a href="{% url "budget:item_delete" item.id %}" class="card-link">Delete</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/budget/item_form.html
{% extends "_admin_base.html" %}
{% block title %} Budget App: Add a new outcome item {% endblock %}

{% block content %}
    <div class="container-fluid p-0">

        <h1 class="h3 mb-3">Create Outcome</h1>

        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0"></h5>
                    </div>
                    <div class="card-body">
                        <div class="container d-flex justify-content-center mt-5" style="width: 25%;">
                            <div class="col mt-5">
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <table class="table">
                                        {{ form.as_table }}
                                    </table>
                                    <div class="container d-flex justify-content-center" style="width: 10%;">
                                        <input type="submit" class="btn btn-primary btn-lg" value="Submit"
                                               style="margin-right: 30px; margin-top: 30px;">
                                        <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;"
                                               onclick="window.location='{% url 'budget:item_list' %}'; return false;"
                                               value="Cancel">
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
{% endblock %}